import { CertificateFrameId, CertificateFrameTheme, CertificateMilestone } from '../types';

export const CERTIFICATE_FRAMES: CertificateFrameTheme[] = [
  {
    id: 'purple',
    name: 'الأرجواني الملكي البهيج',
    icon: '🔮',
    description: 'لوحة متدرجة مبهجة مستوحاة من الأرجواني الملكي والبنفسجي الحيوي ولمسات الذهب',
    previewBg: 'from-purple-600 via-fuchsia-500 to-amber-400',
    outerBorderHex: '#7E22CE',
    innerBorderHex: '#9333EA',
    dashedBorderHex: '#C026D3',
    cornerSymbol: '✦',
    cornerColorHex: '#EAB308',
    plaqueBgHex: '#7E22CE',
    plaqueBorderHex: '#F59E0B',
    plaqueTextHex: '#FFFFFF',
    sealColor1Hex: '#9333EA',
    sealColor2Hex: '#6B21A8',
    sealBorderHex: '#F59E0B',
    accentColorHex: '#A855F7',
    previewOuterBorderClass: 'border-purple-600',
    previewDashedBorderClass: 'border-fuchsia-400',
    previewCornerClass: 'text-amber-500',
    previewPlaqueClass: 'from-purple-700 via-fuchsia-600 to-pink-600 border-amber-400 text-white',
    previewSealClass: 'from-purple-600 to-fuchsia-700 border-amber-400 text-white',
    // Rich gradient & joy styling
    gradientBg: 'linear-gradient(135deg, #FAF5FF 0%, #FDF4FF 40%, #FFFBEB 100%)',
    bannerGradient: 'linear-gradient(135deg, #6B21A8 0%, #9333EA 50%, #C026D3 100%)',
    bannerBorderHex: '#F59E0B',
    bannerTextColorHex: '#FFFFFF',
    primaryTextColorHex: '#3B0764',
    highlightColorHex: '#C026D3',
    statsBgHex: '#FAF5FF',
    statsBorderHex: '#E9D5FF',
    statsTextHex: '#581C87',
    subtleTextColorHex: '#475569',
  },
  {
    id: 'gold',
    name: 'الذهبي الملكي',
    icon: '👑',
    description: 'إطار ذهبي مشرق يعبر عن الفخامة والتفوق والأصالة',
    previewBg: 'from-amber-400 to-yellow-500',
    outerBorderHex: '#F59E0B',
    innerBorderHex: '#D97706',
    dashedBorderHex: '#FBBF24',
    cornerSymbol: '✦',
    cornerColorHex: '#D97706',
    plaqueBgHex: '#FEF3C7',
    plaqueBorderHex: '#F59E0B',
    plaqueTextHex: '#78350F',
    sealColor1Hex: '#FBBF24',
    sealColor2Hex: '#D97706',
    sealBorderHex: '#B45309',
    accentColorHex: '#EC4899',
    previewOuterBorderClass: 'border-amber-400',
    previewDashedBorderClass: 'border-amber-400',
    previewCornerClass: 'text-amber-600',
    previewPlaqueClass: 'from-amber-200 via-amber-100 to-amber-200 border-amber-300 text-amber-950',
    previewSealClass: 'from-amber-400 to-yellow-500 border-amber-600 text-amber-950',
    gradientBg: 'linear-gradient(135deg, #FFFDF8 0%, #FFFBEB 45%, #FEF3C7 100%)',
    bannerGradient: 'linear-gradient(135deg, #B45309 0%, #D97706 50%, #F59E0B 100%)',
    bannerBorderHex: '#FCD34D',
    bannerTextColorHex: '#FFFFFF',
    primaryTextColorHex: '#451A03',
    highlightColorHex: '#B45309',
    statsBgHex: '#FFFBEB',
    statsBorderHex: '#FDE68A',
    statsTextHex: '#78350F',
    subtleTextColorHex: '#475569',
  },
  {
    id: 'pink',
    name: 'وردي البهجة والمرح',
    icon: '🍭',
    description: 'إطار بنكهة غزل بنات سماسم وألوان البهجة والاحتفال',
    previewBg: 'from-pink-500 to-rose-400',
    outerBorderHex: '#EC4899',
    innerBorderHex: '#BE185D',
    dashedBorderHex: '#F472B6',
    cornerSymbol: '✿',
    cornerColorHex: '#DB2777',
    plaqueBgHex: '#FCE7F3',
    plaqueBorderHex: '#EC4899',
    plaqueTextHex: '#831843',
    sealColor1Hex: '#F472B6',
    sealColor2Hex: '#DB2777',
    sealBorderHex: '#9D174D',
    accentColorHex: '#F59E0B',
    previewOuterBorderClass: 'border-pink-400',
    previewDashedBorderClass: 'border-pink-300',
    previewCornerClass: 'text-pink-600',
    previewPlaqueClass: 'from-pink-200 via-rose-100 to-pink-200 border-pink-400 text-pink-950',
    previewSealClass: 'from-pink-400 to-rose-500 border-pink-600 text-white',
    gradientBg: 'linear-gradient(135deg, #FFF1F2 0%, #FDF2F8 50%, #FFFBEB 100%)',
    bannerGradient: 'linear-gradient(135deg, #DB2777 0%, #EC4899 50%, #F43F5E 100%)',
    bannerBorderHex: '#FBBF24',
    bannerTextColorHex: '#FFFFFF',
    primaryTextColorHex: '#831843',
    highlightColorHex: '#DB2777',
    statsBgHex: '#FDF2F8',
    statsBorderHex: '#FBCFE8',
    statsTextHex: '#831843',
    subtleTextColorHex: '#475569',
  },
  {
    id: 'cosmic',
    name: 'فضاء المغامرين',
    icon: '🚀',
    description: 'إطار نيلي ونجوم متلألئة لرواد فضاء ومستكشفي المستقبل',
    previewBg: 'from-indigo-600 to-cyan-500',
    outerBorderHex: '#4F46E5',
    innerBorderHex: '#3730A3',
    dashedBorderHex: '#06B6D4',
    cornerSymbol: '★',
    cornerColorHex: '#06B6D4',
    plaqueBgHex: '#E0E7FF',
    plaqueBorderHex: '#6366F1',
    plaqueTextHex: '#1E1B4B',
    sealColor1Hex: '#818CF8',
    sealColor2Hex: '#4338CA',
    sealBorderHex: '#312E81',
    accentColorHex: '#06B6D4',
    previewOuterBorderClass: 'border-indigo-500',
    previewDashedBorderClass: 'border-cyan-400',
    previewCornerClass: 'text-cyan-500',
    previewPlaqueClass: 'from-indigo-200 via-sky-100 to-cyan-200 border-indigo-400 text-indigo-950',
    previewSealClass: 'from-indigo-500 to-cyan-500 border-indigo-700 text-white',
    gradientBg: 'linear-gradient(135deg, #EEF2FF 0%, #E0F2FE 50%, #F5F3FF 100%)',
    bannerGradient: 'linear-gradient(135deg, #3730A3 0%, #4F46E5 50%, #06B6D4 100%)',
    bannerBorderHex: '#38BDF8',
    bannerTextColorHex: '#FFFFFF',
    primaryTextColorHex: '#1E1B4B',
    highlightColorHex: '#4338CA',
    statsBgHex: '#EEF2FF',
    statsBorderHex: '#C7D2FE',
    statsTextHex: '#312E81',
    subtleTextColorHex: '#475569',
  },
  {
    id: 'emerald',
    name: 'واحة الطبيعة والعلوم',
    icon: '🌱',
    description: 'إطار زمردي منعش يعكس حب الاستكشاف والحياة الطبيعية',
    previewBg: 'from-emerald-500 to-teal-400',
    outerBorderHex: '#10B981',
    innerBorderHex: '#047857',
    dashedBorderHex: '#34D399',
    cornerSymbol: '☘',
    cornerColorHex: '#059669',
    plaqueBgHex: '#D1FAE5',
    plaqueBorderHex: '#10B981',
    plaqueTextHex: '#064E3B',
    sealColor1Hex: '#34D399',
    sealColor2Hex: '#059669',
    sealBorderHex: '#065F46',
    accentColorHex: '#10B981',
    previewOuterBorderClass: 'border-emerald-500',
    previewDashedBorderClass: 'border-emerald-400',
    previewCornerClass: 'text-emerald-600',
    previewPlaqueClass: 'from-emerald-200 via-teal-100 to-emerald-200 border-emerald-400 text-emerald-950',
    previewSealClass: 'from-emerald-400 to-teal-500 border-emerald-700 text-white',
    gradientBg: 'linear-gradient(135deg, #ECFDF5 0%, #F0FDF4 50%, #FFFBEB 100%)',
    bannerGradient: 'linear-gradient(135deg, #065F46 0%, #059669 50%, #10B981 100%)',
    bannerBorderHex: '#6EE7B7',
    bannerTextColorHex: '#FFFFFF',
    primaryTextColorHex: '#064E3B',
    highlightColorHex: '#047857',
    statsBgHex: '#ECFDF5',
    statsBorderHex: '#A7F3D0',
    statsTextHex: '#065F46',
    subtleTextColorHex: '#475569',
  },
  {
    id: 'ocean',
    name: 'أعماق المحيط الساحر',
    icon: '🌊',
    description: 'إطار أزرق فيروزي مستوحى من أسرار البحار والمحيطات العميقة',
    previewBg: 'from-sky-500 to-cyan-400',
    outerBorderHex: '#0284C7',
    innerBorderHex: '#0369A1',
    dashedBorderHex: '#38BDF8',
    cornerSymbol: '✦',
    cornerColorHex: '#0284C7',
    plaqueBgHex: '#E0F2FE',
    plaqueBorderHex: '#0284C7',
    plaqueTextHex: '#0C4A6E',
    sealColor1Hex: '#38BDF8',
    sealColor2Hex: '#0284C7',
    sealBorderHex: '#0369A1',
    accentColorHex: '#0284C7',
    previewOuterBorderClass: 'border-sky-500',
    previewDashedBorderClass: 'border-sky-400',
    previewCornerClass: 'text-sky-600',
    previewPlaqueClass: 'from-sky-200 via-cyan-100 to-sky-200 border-sky-400 text-sky-950',
    previewSealClass: 'from-sky-400 to-cyan-500 border-sky-600 text-white',
    gradientBg: 'linear-gradient(135deg, #F0F9FF 0%, #E0F2FE 50%, #FFFBEB 100%)',
    bannerGradient: 'linear-gradient(135deg, #0369A1 0%, #0284C7 50%, #06B6D4 100%)',
    bannerBorderHex: '#7DD3FC',
    bannerTextColorHex: '#FFFFFF',
    primaryTextColorHex: '#0C4A6E',
    highlightColorHex: '#0284C7',
    statsBgHex: '#F0F9FF',
    statsBorderHex: '#BAE6FD',
    statsTextHex: '#0369A1',
    subtleTextColorHex: '#475569',
  },
];

export function getCertificateFrameTheme(id?: CertificateFrameId): CertificateFrameTheme {
  const found = CERTIFICATE_FRAMES.find((f) => f.id === id);
  return found || CERTIFICATE_FRAMES[0];
}

export const CERTIFICATE_MILESTONES: CertificateMilestone[] = [
  {
    id: 'grand_master',
    title: 'شهادة التفوق الكبرى الشاملة',
    subtitle: 'الشهادة الرسمية الشاملة المعتمدة لجميع إنجازات البطل',
    icon: '🎓',
    frameThemeId: 'purple',
    minPointsRequired: 20,
    description: 'شهادة شاملة ترصد كافة نقاط المعرفة والأوسمة المكتسبة والتحديات المنجزة في سماسم.',
    ribbonTitle: 'شهادة تفوق واكتشاف علمي',
  },
  {
    id: 'junior_scientist_cert',
    title: 'شهادة العالم الصغير للبحث والاستكشاف',
    subtitle: 'تُمنح عند تخطي 150 نقطة والارتقاء لمرتبة العلماء الصغار',
    icon: '🔬',
    frameThemeId: 'emerald',
    minPointsRequired: 150,
    badgeIdRequired: 'junior_scientist',
    description: 'تقدير استثنائي للبطل لدخوله الرسمي نادي العباقرة والعلماء الصغار بامتياز.',
    ribbonTitle: 'شهادة رتبة العالم الصغير',
  },
  {
    id: 'professor_cert',
    title: 'شهادة بروفيسور سماسم الفخرية',
    subtitle: 'أعلى وسام علمي للتتويج بالقمة المعرفية في عائلة سماسم',
    icon: '👑',
    frameThemeId: 'gold',
    minPointsRequired: 250,
    badgeIdRequired: 'professor_grand',
    description: 'التاج المعرفي الأكبر لكل بطل يحقق القمة ويكتشف كافة أسرار العلوم والفيزياء.',
    ribbonTitle: 'شهادة بروفيسور سماسم الفخرية',
  },
  {
    id: 'cosmic_explorer_cert',
    title: 'شهادة مستكشف الفضاء والكواكب',
    subtitle: 'لخوض مغامرات الكواكب والمريخ والنجوم المتلألئة',
    icon: '🚀',
    frameThemeId: 'cosmic',
    badgeIdRequired: 'multiverse_explorer',
    description: 'تكريم شغف ريادة الفضاء واستكشاف أسرار المجرات والكواكب العجيبة.',
    ribbonTitle: 'شهادة مستكشف الفضاء والكون',
  },
  {
    id: 'math_speed_cert',
    title: 'شهادة صاعقة الحساب والذكاء الرياضي',
    subtitle: 'لتحقيق سرعة فائقة في حل العمليات الحسابية والمنطقية',
    icon: '⚡',
    frameThemeId: 'purple',
    badgeIdRequired: 'math_lightning',
    description: 'تقديراً للبديهة السريعة والذكاء الرياضي الفذ في تحدي السرعة الحسابية.',
    ribbonTitle: 'شهادة عبقري الحساب والذكاء',
  },
  {
    id: 'daily_streak_cert',
    title: 'شهادة بطل الالتزام والاستمرار اليومي',
    subtitle: 'للمواظبة الرائعة على حل التحدي العلمي كل يوم بيومه',
    icon: '🌟',
    frameThemeId: 'pink',
    badgeIdRequired: 'daily_streak',
    minChallengesRequired: 3,
    description: 'شهادة فخر بالانضباط اليومي والشغف المستمر لاكتشاف أسرار جديدة بلا انقطاع.',
    ribbonTitle: 'شهادة بطل الالتزام اليومي',
  },
  {
    id: 'simsim_lab_cert',
    title: 'شهادة مبتكر المعمل العجيب',
    subtitle: 'تُمنح لإنجاز التجارب العلمية المنزلية وتفسير ظواهر الطبيعة',
    icon: '🧪',
    frameThemeId: 'emerald',
    badgeIdRequired: 'lab_first_discovery',
    description: 'تقديراً للبطل على إجراء التجارب العلمية واكتشاف قوانين الكيمياء والفيزياء والطبيعة في معمل سماسم.',
    ribbonTitle: 'شهادة مبتكر المعمل العجيب',
  },
];
